### ISSUE TITLE
Lost messages when consumer restart

### ISSUE THREAD

**Issue by wattgo** [b/kafka-websocket#3]
Hi !
Im producing every second a message on a test topic "topicABC". Kafka-websocket producer is in 'sync' mode.
My consumer has the group.id "test-group" using your client.rb script.
I configured kafka-websocket consumer with the "auto.offset.reset=smallest" option to give the opportunity to my consumer to fetch missing messages if it stops.
Everything works fine except that the consumer always loose 5 or 6 messages (5 or 6 seconds of messages) when it restart.

$ ./client-consumer.rb 
[:open]
[:message, "{\"topic\":\"topicABC\",\"message\":\"Tue May 06 2014 17:56:02 GMT+0200 (CEST)\"}"]
[:message, "{\"topic\":\"topicABC\",\"message\":\"Tue May 06 2014 17:56:03 GMT+0200 (CEST)\"}"]
[:message, "{\"topic\":\"topicABC\",\"message\":\"Tue May 06 2014 17:56:04 GMT+0200 (CEST)\"}"]
[:message, "{\"topic\":\"topicABC\",\"message\":\"Tue May 06 2014 17:56:05 GMT+0200 (CEST)\"}"]
[:message, "{\"topic\":\"topicABC\",\"message\":\"Tue May 06 2014 17:56:06 GMT+0200 (CEST)\"}"]
^C

// waiting few seconds to restart

$ ./client-consumer.rb 
[:open]
[:message, "{\"topic\":\"topicABC\",\"message\":\"Tue May 06 2014 17:56:12 GMT+0200 (CEST)\"}"]
[:message, "{\"topic\":\"topicABC\",\"message\":\"Tue May 06 2014 17:56:13 GMT+0200 (CEST)\"}"]
[:message, "{\"topic\":\"topicABC\",\"message\":\"Tue May 06 2014 17:56:14 GMT+0200 (CEST)\"}"]
[:message, "{\"topic\":\"topicABC\",\"message\":\"Tue May 06 2014 17:56:15 GMT+0200 (CEST)\"}"]
[:message, "{\"topic\":\"topicABC\",\"message\":\"Tue May 06 2014 17:56:16 GMT+0200 (CEST)\"}"]
^C

Messages at 17:56:07, 08, 09, 10, 11 havent been consumed at all.
I did some debug and KafkaConsumer.java from kafka-websocket doesnt get these messages too 
Maybe some stream issue ?

**Comment by FreeSlaver** [comment]
good job,Thanks
